### ISSUE TITLE
Option for the minimum length of autocomplete

### ISSUE THREAD

**Issue by AleBelletti** [gruppoanthea-it/dynamic-form-lib#2]
i need that the autocomplete, will start the call to the service, just after n inserted char. 

Example: 

1) write A => nothing
2) write Al => nothing
3) write Ale => ApiCall => result: Alexandria/Alessandria/Aleppo

**Comment by mattia-mattiuzzo** [comment]
Added in d5ca511f70720969ca66cdba993d391f4d41274c
