### ISSUE TITLE
Wrong import

### ISSUE THREAD

**Issue by AleBelletti** [gruppoanthea-it/dynamic-form-lib#4]
in projects/dynamic-form-lib/src/lib/services/dynamic-form.service.ts

there is a wrong import:

import { SchemaRetrieve, DataRetrieve } from 'projects/dynamic-form-lib/src/public_api';

Should be : import { SchemaRetrieve, DataRetrieve } from '../../public_api';

**Comment by mattia-mattiuzzo** [comment]
Fixed with 64404985ad496bd0be39e2631c6d1d7c7dbdbdff
